FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code (Week 1-6)
COPY . .

# Expose port
EXPOSE 8000

# Run commands
CMD ["python", "week 5/src/main.py"]
